apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database-deployment
  labels:
    app: {{ .Release.Name }}-database
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-database
    spec:
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc-database
      containers:
        - name: {{ .Release.Name }}-database
          image: postgres
          envFrom:
            - secretRef:
                name: env-database
          env:
            - name: PGDATA
              value: /data/postgres-data
          ports:
            - containerPort: 5432
          volumeMounts:
          - name: pv-storage
            mountPath: /data
