apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-service
  labels:
    app: {{ .Release.Name }}-database
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  internalTrafficPolicy: Local
  selector:
    app: {{ .Release.Name }}-database
