apiVersion: v1
kind: Service
metadata:
  name: open-tombola-database-service
  labels:
    app: open-tombola-database
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  internalTrafficPolicy: Local
  selector:
    app: open-tombola-database
